CREATE TABLE `candidate_outreach` (
	`id` text PRIMARY KEY NOT NULL,
	`tenant_id` text DEFAULT 'default' NOT NULL,
	`candidate_id` text NOT NULL,
	`job_brief_id` text NOT NULL,
	`channel` text NOT NULL,
	`message_type` text NOT NULL,
	`content` text NOT NULL,
	`status` text DEFAULT 'draft' NOT NULL,
	`sent_at` text,
	`replied_at` text,
	`created_at` text DEFAULT (datetime('now')),
	FOREIGN KEY (`candidate_id`) REFERENCES `candidates`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`job_brief_id`) REFERENCES `job_briefs`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `candidates` (
	`id` text PRIMARY KEY NOT NULL,
	`tenant_id` text DEFAULT 'default' NOT NULL,
	`job_brief_id` text NOT NULL,
	`provider_id` text NOT NULL,
	`linkedin_url` text,
	`first_name` text,
	`last_name` text,
	`headline` text,
	`current_company` text,
	`current_title` text,
	`location` text,
	`email` text,
	`fit_score` integer,
	`fit_reason` text,
	`fit_breakdown` text,
	`pipeline_status` text DEFAULT 'Sourced' NOT NULL,
	`shortlisted` integer DEFAULT false,
	`shortlist_rank` integer,
	`connect_sent_at` text,
	`connected_at` text,
	`dm1_sent_at` text,
	`dm2_sent_at` text,
	`replied_at` text,
	`email1_sent_at` text,
	`email_replied_at` text,
	`source` text DEFAULT 'crustdata' NOT NULL,
	`raw_data` text,
	`notion_page_id` text,
	`created_at` text DEFAULT (datetime('now')),
	`updated_at` text DEFAULT (datetime('now')),
	FOREIGN KEY (`job_brief_id`) REFERENCES `job_briefs`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `job_briefs` (
	`id` text PRIMARY KEY NOT NULL,
	`tenant_id` text DEFAULT 'default' NOT NULL,
	`title` text NOT NULL,
	`seniority` text NOT NULL,
	`skills` text NOT NULL,
	`nice_to_have_skills` text,
	`location` text NOT NULL,
	`remote_policy` text DEFAULT 'hybrid' NOT NULL,
	`salary_min` integer,
	`salary_max` integer,
	`salary_currency` text DEFAULT 'EUR' NOT NULL,
	`open_signals` text,
	`disqualify_signals` text,
	`client_name` text,
	`status` text DEFAULT 'draft' NOT NULL,
	`notion_page_id` text,
	`created_at` text DEFAULT (datetime('now')),
	`updated_at` text DEFAULT (datetime('now'))
);
